Repository redshiftrobotics/8032, pull requests merged in 2020-01, with the labels that each got.

#3 Add comment
  robot.py
Labels: invalid

#13 Add Button Debouncing
  limelight.py
  robot.py
Labels: enhancement

#18 Implement state class for robot state management
  robot.py
  state.py
Labels: enhancement, help wanted
